env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - google
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
  - "react-hooks"
rules:
  max-len: off # Can't get it to work properly 
    # - 1
    # - code: 100
    # - comments: 100
    # - ignoreUrls: true
  react/prop-types: off
  require-jsdoc: off
  indent: ["error", 4]
  object-curly-spacing: 
  - 2
  - "always"
  react-hooks/rules-of-hooks: 
  - "error"
  react-hooks/exhaustive-deps: 
  - "warn"
  operator-linebreak:
  - 2
  - "before"
  react/react-in-jsx-scope: "off" # Not needed since we're using >= React 17
  