# env:
#   browser: true
#   es2021: true
# extends:
#   - plugin:react/recommended
#   - google
# parser: "@typescript-eslint/parser"
# parserOptions:
#   ecmaFeatures:
#     jsx: true
#   ecmaVersion: 13
#   sourceType: module
# settings:
#   react:
#     version: detect
# plugins:
#   - react
#   - "@typescript-eslint"
#   - "react-hooks"
#   - import
# rules:
#   max-len: off # Can't get it to work properly 
#   require-jsdoc: off
#   indent: ["error", 4, { "SwitchCase": 1 }]
#   object-curly-spacing: 
#   - 2
#   - "always"
#   react-hooks/rules-of-hooks: error
#   react-hooks/exhaustive-deps: error
#   operator-linebreak:
#   - 2
#   - "before"
#   import/no-default-export: error
#   import/export: error
  
#   # Base rule must be deactivated because it reports incorrect errors: https://typescript-eslint.io/rules/no-invalid-this/
#   no-invalid-this: off
#   "@typescript-eslint/no-invalid-this": error

#   no-unused-vars: off
#   "@typescript-eslint/no-unused-vars": error

#   react/prop-types: off
#   react/react-in-jsx-scope: off # Not needed since we're using >= React 17
#   react/jsx-closing-tag-location: error
#   react/jsx-closing-bracket-location: error
#   react/jsx-wrap-multilines: error
#   react/hook-use-state: error
#   react/no-danger: error
#   react/no-this-in-sfc: error
#   react/no-unsafe: error
#   react/no-unstable-nested-components: error
#   react/jsx-curly-brace-presence: error
#   react/jsx-no-useless-fragment: error
  