name: EAS Build
on:
  workflow_run:
      workflows: [test]
      branches: [main, dev/fix-build-job]
      types:
        - completed
jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Install and build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: npm ci
      - name: Build on EAS
        run: eas build --platform android --non-interactive